# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba222f996aaa5b8f62e2686eecda8ccc7810c8266fc038e1349c0caf419893fa99c01bd9f2f6608192ddd419fcbb3d4ecaf93cfa4a39748d4369ed2971432ba9

test:
  secret_key_base: d5b8f3c5c56ae88420107da6d8076f5a27e705c011b41b9035056f6ecd4897340cf871826202ce5e464ea7a74452a3bf80f689cc7d9e9222799ee21f758ee4d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
